{% set name = "glacier" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glacier-{{ version }}.tar.gz
  sha256: b2a98d556d08d87620551bc6603c110178258d8b47b483d8f53c28be5329721b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - click >=8.0.4,<9.0.0
    - click-help-colors >=0.9.1,<0.10.0
    - importlib-metadata >=4.11.3,<5.0.0
    - python >={{ python_min }}
    - typing_extensions >=4.1.1,<5.0.0

test:
  imports:
    - glacier
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/relastle/glacier
  summary: A python CLI building library for minimalists.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
