{% set name = "glacier" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/glacier-{{ version }}.tar.gz
  sha256: c3d5fab651f787ab6538350becbe983002a8d0a0992c526d53231bc09e475ff9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - click >=8.1.8
    - click-help-colors >=0.9.4
    # Not listed upstream but needed
    - typing_extensions

test:
  imports:
    - glacier
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/relastle/glacier
  summary: A python CLI building library for minimalists.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
