{% set name = "glacier" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glacier-{{ version }}.tar.gz
  sha256: 534414f6fc1cfcc6f76fd9747b378cde79974c67dffab18b9991e4b67e100b3e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - click >=8.0.4,<9.0.0
    - click-help-colors >=0.9.1,<0.10.0
    - importlib-metadata >=4.11.3,<5.0.0
    - python >=3.6
    - typing_extensions >=4.1.1,<5.0.0

test:
  imports:
    - glacier
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/relastle/glacier
  summary: A python CLI building library for minimalists.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
